### ISSUE TITLE
Modifier le message de validation

### ISSUE THREAD

**Issue by apeyroux** [kpym/autoradio-renault#1]
L'application marche très bien toutefois le dernier message mériterait peut-être une petite modification pour les novices comme moi : 

Maintenez appuyé sur le bouton 6 (ou 5) pour terminer.

Au lieu de :

Appuyer sur le bouton 6 (ou 5) pour terminer.

Merci pour votre travail !

**Comment by kpym** [comment]
Merci pour la suggestion. C'est corrigé dans 727324fb445.
